name: captain
favicon: null
layout_spectrum: 0.8743495226372033
typography_spectrum: 0.9593761556316167
title: 'The sky is the limit!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a92f1'
    - '#ffffff'
    - '#7dc5f7'
    - '#d1eafc'
    - '#56b4f5'
  brandStrength: 0.7358623293694109
  lightness: 0.5477836383506656
  saturation: 0.7026613170746714
  rhythmicContrast: 0.7123129253741354
purpose: []
